export const FONT_LINK =
  "https://fonts.googleapis.com/css2?family=DM+Sans:ital,opsz,wght@0,9..40,300;0,9..40,500;0,9..40,700;1,9..40,300&family=Space+Mono:wght@400;700&display=swap";

export const TERMS_CONTENT = [
  { type: "h1", text: "Terms of Use" },
  { type: "subtitle", text: "Settlement Calculator — Property Loss Claim Portal" },
  { type: "date", text: "Effective Date: February 24, 2026" },
  { type: "h2", text: "1. Acceptance of Terms" },
  { type: "p", text: 'By accessing or using the Settlement Calculator portal (the "Service"), you agree to be bound by these Terms of Use ("Terms"). If you do not agree to these Terms, you may not access or use the Service.' },
  { type: "h2", text: "2. Description of Service" },
  { type: "p", text: "The Service is a secure online portal that allows users to upload documentation—including photographs, receipts, voice memos, and supplemental context—related to property loss insurance claims. The Service processes this information to assist in calculating settlement values for claimed items." },
  { type: "h2", text: "3. Eligibility and Access" },
  { type: "p", text: "Access to the Service is restricted to authorized users who have been provided valid credentials (an email address and entry code). You must not share your access credentials with any third party. You are responsible for all activity that occurs under your account." },
  { type: "h2", text: "4. User Obligations" },
  { type: "p", text: "When using the Service, you agree to:" },
  { type: "li", text: "Provide accurate, truthful, and complete information regarding your property loss claim." },
  { type: "li", text: "Upload only files and content that you own or have the right to submit." },
  { type: "li", text: "Not attempt to access the Service using another person's credentials." },
  { type: "li", text: "Not upload malicious files, viruses, or any content intended to disrupt the Service." },
  { type: "li", text: "Comply with all applicable laws and regulations." },
  { type: "h2", text: "5. Accuracy of Submissions" },
  { type: "p", text: "You acknowledge that the information you submit may be used in connection with an insurance claim. Submitting false, misleading, or fraudulent information may constitute insurance fraud and could result in civil or criminal penalties under applicable law." },
  { type: "h2", text: "6. Intellectual Property" },
  { type: "p", text: "All content, design, software, and technology comprising the Service are the property of the Service operator and are protected by intellectual property laws. You retain ownership of any files you upload but grant us a limited license to process, store, and use your uploaded content solely for the purpose of providing the Service." },
  { type: "h2", text: "7. Settlement Calculations" },
  { type: "p", text: "The Service provides estimated settlement values based on the information you submit. These calculations are for informational and reference purposes only. They do not constitute a binding offer, guarantee of payment, or final settlement determination. Actual settlement amounts are determined by your insurance carrier in accordance with your policy terms." },
  { type: "h2", text: "8. Limitation of Liability" },
  { type: "p", text: "To the maximum extent permitted by law, the Service operator shall not be liable for any indirect, incidental, special, consequential, or punitive damages arising out of or related to your use of the Service, including but not limited to errors in settlement calculations, data loss, or service interruptions. Our total liability shall not exceed the amount you have paid (if any) to use the Service." },
  { type: "h2", text: "9. Disclaimer of Warranties" },
  { type: "p", text: 'The Service is provided "as is" and "as available" without warranties of any kind, whether express or implied, including but not limited to implied warranties of merchantability, fitness for a particular purpose, and non-infringement.' },
  { type: "h2", text: "10. Indemnification" },
  { type: "p", text: "You agree to indemnify and hold harmless the Service operator, its affiliates, officers, and employees from any claims, damages, losses, or expenses arising out of your use of the Service, your violation of these Terms, or your submission of inaccurate or fraudulent information." },
  { type: "h2", text: "11. Termination" },
  { type: "p", text: "We may suspend or terminate your access to the Service at any time, with or without cause or notice. Upon termination, your right to use the Service ceases immediately. Sections relating to intellectual property, limitation of liability, indemnification, and governing law shall survive termination." },
  { type: "h2", text: "12. Modifications to Terms" },
  { type: "p", text: "We reserve the right to modify these Terms at any time. Updated Terms will be posted on the Service. Your continued use of the Service after changes are posted constitutes acceptance of the revised Terms." },
  { type: "h2", text: "13. Governing Law" },
  { type: "p", text: "These Terms shall be governed by and construed in accordance with the laws of the applicable jurisdiction, without regard to conflict of law principles." },
  { type: "h2", text: "14. Contact" },
  { type: "p", text: "If you have any questions about these Terms, please contact us through the channels provided by your claims representative." },
];

export const PRIVACY_CONTENT = [
  { type: "h1", text: "Privacy Policy" },
  { type: "subtitle", text: "Settlement Calculator — Property Loss Claim Portal" },
  { type: "date", text: "Effective Date: February 24, 2026" },
  { type: "h2", text: "1. Introduction" },
  { type: "p", text: 'This Privacy Policy describes how the Settlement Calculator portal (the "Service") collects, uses, stores, and protects your personal information when you use the Service to submit property loss claim documentation. We are committed to safeguarding your privacy and handling your data responsibly.' },
  { type: "h2", text: "2. Information We Collect" },
  { type: "h3", text: "2.1 Information You Provide" },
  { type: "p", text: "When you use the Service, we collect information that you directly provide, including:" },
  { type: "li", text: "Email address used for authentication and account identification." },
  { type: "li", text: "Entry codes used to verify your authorized access." },
  { type: "li", text: "Uploaded files, including photographs of items, receipts, and voice memos related to your property loss claim." },
  { type: "li", text: "Additional context you provide in text form to assist with item identification (such as clothing gender, preferred retailers, or item categories)." },
  { type: "li", text: "Value type selections (actual replacement costs or unreplaced item values) and upload type classifications." },
  { type: "h3", text: "2.2 Information Collected Automatically" },
  { type: "p", text: "When you access the Service, we may automatically collect:" },
  { type: "li", text: "Browser type and version." },
  { type: "li", text: "IP address." },
  { type: "li", text: "Date and time of access." },
  { type: "li", text: "Pages viewed and actions taken within the Service." },
  { type: "h2", text: "3. How We Use Your Information" },
  { type: "p", text: "We use the information we collect for the following purposes:" },
  { type: "li", text: "To authenticate your identity and authorize access to the Service." },
  { type: "li", text: "To process, analyze, and categorize your uploaded claim documentation." },
  { type: "li", text: "To generate settlement value calculations based on submitted materials." },
  { type: "li", text: "To improve the accuracy and functionality of the Service." },
  { type: "li", text: "To communicate with you regarding your submissions or account." },
  { type: "li", text: "To comply with legal obligations and respond to lawful requests." },
  { type: "h2", text: "4. Data Processing and AI" },
  { type: "p", text: "The Service uses automated processing, which may include artificial intelligence and machine learning technologies, to analyze uploaded images, receipts, and audio files. This processing is used to identify items, estimate replacement values, and generate settlement calculations. Human review may also be applied to verify or supplement automated results." },
  { type: "h2", text: "5. Data Sharing and Disclosure" },
  { type: "p", text: "We do not sell your personal information. We may share your information in the following circumstances:" },
  { type: "li", text: "With insurance carriers and adjusters involved in processing your claim, as necessary to fulfill the purpose of the Service." },
  { type: "li", text: "With third-party service providers who assist in operating the Service (such as cloud hosting and data processing providers), subject to confidentiality obligations." },
  { type: "li", text: "When required by law, subpoena, court order, or other legal process." },
  { type: "li", text: "To protect the rights, property, or safety of the Service operator, its users, or the public." },
  { type: "h2", text: "6. Data Retention" },
  { type: "p", text: "We retain your personal information and uploaded files for as long as necessary to fulfill the purposes described in this Privacy Policy, including to complete the processing of your claim. After the claim process is concluded, we may retain data for a reasonable period to comply with legal obligations, resolve disputes, and enforce our agreements. You may request deletion of your data by contacting us." },
  { type: "h2", text: "7. Data Security" },
  { type: "p", text: "We implement appropriate technical and organizational measures to protect your personal information against unauthorized access, alteration, disclosure, or destruction. These measures include encryption of data in transit and at rest, access controls, and regular security assessments. However, no method of transmission over the internet or electronic storage is completely secure, and we cannot guarantee absolute security." },
  { type: "h2", text: "8. Your Rights" },
  { type: "p", text: "Depending on your jurisdiction, you may have the following rights regarding your personal information:" },
  { type: "li", text: "Right to access the personal information we hold about you." },
  { type: "li", text: "Right to request correction of inaccurate information." },
  { type: "li", text: "Right to request deletion of your personal information." },
  { type: "li", text: "Right to restrict or object to certain processing of your data." },
  { type: "li", text: "Right to data portability (receiving your data in a structured, machine-readable format)." },
  { type: "li", text: "Right to withdraw consent where processing is based on consent." },
  { type: "p", text: "To exercise any of these rights, please contact us through the channels provided by your claims representative." },
  { type: "h2", text: "9. Cookies and Tracking" },
  { type: "p", text: "The Service may use essential cookies or similar technologies to maintain your session and ensure the Service functions correctly. We do not use third-party advertising or analytics tracking cookies." },
  { type: "h2", text: "10. Children's Privacy" },
  { type: "p", text: "The Service is not directed to individuals under the age of 18. We do not knowingly collect personal information from children. If we become aware that we have collected information from a child, we will take steps to delete it promptly." },
  { type: "h2", text: "11. Changes to This Policy" },
  { type: "p", text: "We may update this Privacy Policy from time to time. The revised policy will be posted on the Service with an updated effective date. Your continued use of the Service after changes are posted constitutes acceptance of the revised Privacy Policy." },
  { type: "h2", text: "12. Contact" },
  { type: "p", text: "If you have any questions about this Privacy Policy or our data practices, please contact us through the channels provided by your claims representative." },
];